## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [2]:
import numpy as np
array = np.array([[1.1,1.2,1.3,1.4,1.5,1.6],[2.1,2.2,3.2,3.3,4.3,2.5],[5.2,5.3,5.1,4.6,1.8,8.3]])
array

array([[1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
       [2.1, 2.2, 3.2, 3.3, 4.3, 2.5],
       [5.2, 5.3, 5.1, 4.6, 1.8, 8.3]])

Check the dimension you have created is correct (use “*.shape*”)

In [3]:
array.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [6]:
array[1,4] = 19.75
array

array([[ 1.1 ,  1.2 ,  1.3 ,  1.4 ,  1.5 ,  1.6 ],
       [ 2.1 ,  2.2 ,  3.2 ,  3.3 , 19.75,  2.5 ],
       [ 5.2 ,  5.3 ,  5.1 ,  4.6 ,  1.8 ,  8.3 ]])

Extract the 2nd and the 3rd row of the array you created. 

In [7]:
array[1:]

array([[ 2.1 ,  2.2 ,  3.2 ,  3.3 , 19.75,  2.5 ],
       [ 5.2 ,  5.3 ,  5.1 ,  4.6 ,  1.8 ,  8.3 ]])