## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [6]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

data = pd.read_csv('MSFT_2000.csv', index_col = 'Date')

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [7]:
drift.values

array([-3.42521946e-05])

In [8]:
stdev.values

array([0.01939682])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [9]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [12]:
daily_returns = np.exp(drift.values + stdev.values * (norm.ppf(np.random.rand(t_intervals,iterations))))
daily_returns

array([[0.99603283, 0.99932648, 1.01977792, ..., 0.98166523, 1.00855844,
        1.01316388],
       [1.00165655, 1.00557251, 1.01112039, ..., 1.01468358, 1.04044541,
        0.98918171],
       [1.03018718, 1.00651328, 0.98560469, ..., 1.00201061, 1.02139871,
        1.0338937 ],
       ...,
       [1.00080922, 0.99396785, 0.98453239, ..., 0.97959899, 0.96833658,
        1.02800306],
       [0.98630679, 0.97676238, 1.00122856, ..., 1.01602987, 0.95002636,
        1.00267208],
       [1.05350181, 1.01197131, 0.95904536, ..., 0.97505272, 0.99380786,
        0.97883741]], shape=(250, 10))